#!/bin/zsh

GLOBIGNORE=".:.."

for file in .*; do
    [[ "${file}" == ".git" || "${file}" == ".gitignore" ]] && continue 1
    [[ "$1" == "-debug" ]] && echo "ln -s $(pwd)${file} ~/"${file}"" && continue 1
    [[ -h ~/"${file}" ]] && echo -e "\e[94m${file} \e[92malready linked\e[0m" && continue 1
    echo -e "\e[96mLinking \e[94m${file}\e[0m"
    /bin/ln -s "$(pwd)/${file}" ~/"${file}"
done

/bin/ln -s "$(pwd)/mybin" ~/".local"/mybin
